services:
  server:
    container_name: server
    restart: on-failure
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    # command: bash -c "alembic upgrade head && gunicorn -b 0.0.0.0:8000 -w 5 -k uvicorn.workers.UvicornWorker src.main:app"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server/src:/app/src
      - ./server/alembic:/app/alembic
      - ./server/tests:/app/tests
      - ./server/pyproject.toml:/app/pyproject.toml
      - ./server/uv.lock:/app/uv.lock
      - ./server/alembic.ini:/app/alembic.ini
      - ./server/.env:/app/.env
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    env_file:
      - ./.postgres-env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./.postgres-env
    depends_on:
      - db

volumes:
  postgres_data: