"""Add user subsctiptions

Revision ID: 2e6c89f8995c
Revises: 5b1228e0cb86
Create Date: 2025-05-20 14:15:54.662328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e6c89f8995c"
down_revision: Union[str, None] = "5b1228e0cb86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("subscriber_id", sa.Uuid(), nullable=False),
        sa.Column("subscribed_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscribed_id"], ["users.user_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subscriber_id"], ["users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("subscriber_id", "subscribed_id"),
    )
    op.add_column("users", sa.Column("subscribers_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "subscribers_count")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
