"""Add pg_trgm extension

Revision ID: ab61424177af
Revises: c98896edf2f2
Create Date: 2025-03-27 20:40:36.961206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab61424177af"
down_revision: Union[str, None] = "c98896edf2f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute("SET pg_trgm.similarity_threshold = 0.15;")

    op.create_index(
        "users_username_trgm_idx",
        "users",
        ["username"],
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("users_username_trgm_idx", table_name="users")
    # ### end Alembic commands ###
